version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "3060:3060"
    environment:
      PRISMA_CONFIG: |
        port: 3060
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  
  backend:
    build:
      context: ./
      dockerfile: .dockerfiles/backendDev
    ports:
      - "${REACT_APP_BACKEND_PORT_DEV}:${REACT_APP_BACKEND_PORT_DEV}"
    volumes:
      - ./backend:/opt/app
    depends_on:
      - prisma
    restart: always
    environment: 
      NODE_ENV: development
      BACKEND_PORT: ${REACT_APP_BACKEND_PORT_DEV}
      SALT_ROUNDS: ${SALT_ROUNDS}
      JWT_SECRET: ${JWT_SECRET}
      USE_AUTH: ${USE_AUTH}
    env_file: .env

  postgres:
    image: postgres
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    # ports:
    # - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    build:
      context: ./
      dockerfile: .dockerfiles/frontendDev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules/.cache/
    environment:
      NODE_ENV: development
      REACT_APP_BACKEND_PORT_DEV: ${REACT_APP_BACKEND_PORT_DEV}
      REACT_APP_BACKEND_PORT_PROD: ${REACT_APP_BACKEND_PORT_PROD}
      REACT_APP_PUBLIC_URL: ${REACT_APP_PUBLIC_URL}

    restart: always

volumes:
  postgres:



  
